### ISSUE TITLE
add a note that says this is only useful for 2.3

### ISSUE THREAD

**Issue by cordoval** [Incenteev/IncenteevTranslationCheckerBundle#3]
if the project is 2.6+ then make sure you use the debug:translation command already in symfony

**Comment by stof** [comment]
Well, the commands in this bundle allow to do a few things not possible with ``debug:translation``. One of these thing being exiting with a non-0 exit code in ``incenteev:translation:compare`` when a translation is incomplete, which can be used on a CI server.

**Comment by cordoval** [comment]
:+1:
