### ISSUE TITLE
deprecate the bundle

### ISSUE THREAD

**Issue by cordoval** [Incenteev/IncenteevTranslationCheckerBundle#5]
sf2.7-8 already has this built-in, let's deprecate the bundle

**Comment by stof** [comment]
Please stop reopening the same issue again: https://github.com/Incenteev/IncenteevTranslationCheckerBundle/issues/3

**Comment by cordoval** [comment]
oh sorry, my short memory failed me. I just reused the bundle then had to remove it since in 2.7 i was able to do all without the bundle. It could at least justify a note about this on the README.md
