### ISSUE TITLE
invalid argument dupplied foreach

### ISSUE THREAD

**Issue by wickedOne** [Incenteev/IncenteevTranslationCheckerBundle#9]
the [``cache_dir``](https://github.com/Incenteev/IncenteevTranslationCheckerBundle/blob/master/DependencyInjection/Compiler/ConfigureTranslatorPass.php#L29) is added to the ``$loaderIds`` rather than the ``$options`` argument of the translator [constructor](https://github.com/symfony/framework-bundle/blob/86119a17ed2547afa0dc0286631c98338e3dc3a3/Translation/Translator.php#L57) and thereby crashes the initialize function of the translator.

**Comment by stof** [comment]
@wickedOne I released v1.2.1 with a fix for Symfony 3.3 compatibility.

**Comment by wickedOne** [comment]
thanks @stof, much appreciated!
